Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
Traceback (most recent call last):
  File "DecisionTree.py", line 34, in <module>
    Xte, Yte = readXY(sys.argv[7], sys.argv[8])
  File "DecisionTree.py", line 10, in readXY
    for line in open(xf):
IOError: [Errno 2] No such file or directory: '../../../corpora/es-en/features/dataset2_test.features_noppl'
